name: ci

# default values to use


# run the workflow for different events
# on every commit
# and every morning
# and when we trigger the workflow manually
# and when we dispatch an event
on:
  push:
  workflow_dispatch:
  schedule:
    # UTC time
    - cron: '0 7 * * *'
  repository_dispatch:
    types: [on-greeting]
jobs:
  greet:
    runs-on: macos-latest
    steps:
      - run: echo "Job done." 

