name: ci

# default values to use
env:
  greeting: 'Hello'
  n: 1

# run the workflow for different events
# on every commit
# and every morning
# and when we trigger the workflow manually
# and when we dispatch an event
on:
  push:
  workflow_dispatch:
    inputs:
      n:
        description: Magic number
        type: number
        default: 0
        required: false
      greeting:
        description: A greeting message
        type: string
        default: ''
        required: false
  schedule:
    # UTC time
    - cron: '0 7 * * *'
  repository_dispatch:
    types: [on-greeting]
jobs:
  greet:
    runs-on: macos-latest
    steps:
      - run: echo "Job done." 

